### PR TITLE
Prepare for conversion

### PR DESCRIPTION
**Pull request by Stoppedwumm**

### CODE REVIEW

**Comment by Stoppedwumm** [comment]
I'm gonna test the code

**Comment by Stoppedwumm** [comment]
We have some problems converting:
# It simply takes too long!

**Comment by StoppedwummSites** [comment]
I got something better than moviepy

# ffmpeg-python

**Comment by StoppedwummSites** [comment]
We might need to check on mac

**Comment by StoppedwummSites** [comment]
I updated the build to include linux

**Comment by StoppedwummSites** [comment]
We will try merging in a few seconds

**Review by StoppedwummSites — APPROVED** [review]
We are going to merge

Approved

**Pull request merged**
